src/ru/samis/questionnaire/GeoBean.java
package ru.samis.questionnaire;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import javax.servlet.http.Part;

import ru.samis.geoclusters.Clustering;
import ru.samis.geoclusters.Main;
import ru.samis.geoclusters.entities.Cluster;
import ru.samis.geoclusters.entities.ClustersWithTimeline;
import ru.samis.geoclusters.entities.Location;
import ru.samis.geoclusters.entities.Place;
import ru.samis.geoclusters.entities.Route;
import ru.samis.questionnaire.db.DataBase;

@ManagedBean(name = "geo")
@SessionScoped
public class GeoBean {
    public GeoBean() {
//        startNewSession();
//        loadClusters();
    }

    private String sessionId;

    public String getSessionId() {
        return sessionId;
    }

    private ClustersWithTimeline<Cluster<Location>> clusters = null;
    private Place[] places = null;
    private List<Route> routes = null;
    private Part file;

    private int radius = Main.MAX_RADIUS;
    private double minSizeRatio = Main.MIN_SIZE_RATIO,
            errorMeters = Main.ERROR_METERS;

    public int getRadius() {
        return radius;
    }

    public void setRadius(int radius) {
        this.radius = radius;
    }

    public double getMinSizeRatio() {
        return minSizeRatio;
    }

    public void setMinSizeRatio(double minSizeRatio) {
        this.minSizeRatio = minSizeRatio;
    }

    public double getErrorMeters() {
        return errorMeters;
    }

    public void setErrorMeters(double errorMeters) {
        this.errorMeters = errorMeters;
    }

    public ClustersWithTimeline<Cluster<Location>> getClusters() {
        return clusters;
    }

    public void setClusters(ClustersWithTimeline<Cluster<Location>> clusters) {
        this.clusters = clusters;
    }

    public void startNewSession() {
        FacesContext fCtx = FacesContext.getCurrentInstance();
        fCtx.getExternalContext().invalidateSession();
        HttpSession session = (HttpSession) fCtx.getExternalContext().getSession(true);

        sessionId = session.getId();

    }

    public void loadClusters() {
        try {
            FileInputStream in = new FileInputStream("/media/Data/Documents/tmp/clusters.bin");

            ObjectInputStream objectInputStream = new ObjectInputStream(in);
            clusters = (ClustersWithTimeline<Cluster<Location>>) objectInputStream.readObject();

            in.close();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    private String fileName;

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Part getFile() {
        return file;
    }

    public void setFile(Part file) {
        this.file = file;
        processTakeout();
        this.file = null;
    }

    public void processTakeout() {
        if (file == null) {
            return;
        }

//        new Thread(() -> {
        InputStream in = null;
        try {
            in = file.getInputStream();

            setClusters(null);
            ClustersWithTimeline<Cluster<Location>> clusters = null;
            if (fileName.endsWith("zip")) {
                clusters = Main.takeoutZipToClusters(in, 1496271600,
                                                     radius, minSizeRatio, errorMeters);
            } else if (fileName.endsWith("json")) {
                clusters = Main.takeoutJsonToClusters(in, 1496271600,
                                                      radius, minSizeRatio, errorMeters);
            }
            in.close();
            setClusters(clusters);
        } catch (IOException e) {
            e.printStackTrace();
        }

//        }).start();
    }

    public void doNothing() {

    }

    public Place[] getPlaces() {
        return places;
    }

    public void setPlaces(Place[] places) {
        this.places = places;
    }

    private String routesJson;

    public String getRoutesJson() {
        return routesJson;
    }

    public void setRoutesJson(String routesJson) {
        this.routesJson = routesJson;
        JSONArray array = new JSONArray(routesJson);
        int length = array.length();
        routes = new ArrayList<>(length);
        Route route;

        JSONObject object;
        for (int i = 0; i < length; i++) {
            object = array.getJSONObject(i);

            routes.add(route = new Route());
            route.setSessionId(sessionId);

            route.setGeometry(object.optString("geometry"));
            route.setMoveKinds(object.optString("moveKinds"));
            route.setPeriodic(object.optString("periodic"));
            route.setWeight(object.optInt("weight"));
        }

        try {
            DataBase db = DataBase.getInstance();
            db.insertRoutes(routes);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public String getPointsJson() {
        return "";
    }

    public void setPointsJson(String json) {
        JSONArray array = new JSONArray(json);
        int length = array.length(), id;
        places = new Place[length];
        JSONObject object;

        List<Cluster<Cluster<Location>>> clustersLeft = new ArrayList<>();
        List<Place> placesList = new ArrayList<>();
        Cluster cluster;

        for (int i = 0; i < length; i++) {
            object = array.getJSONObject(i);

            places[i] = new Place();
            places[i].setLat(object.optDouble("x1"));
            places[i].setLng(object.optDouble("y1"));
            places[i].setLat2(object.optDouble("x2"));
            places[i].setLng2(object.optDouble("y2"));

            places[i].name = object.optString("name");
            places[i].typeStr = object.optString("type").toLowerCase();
            places[i].type = Place.TYPE_TO_MASK.get(places[i].typeStr);
            places[i].likeStr = object.optString("likeThisPlace").toLowerCase();
            places[i].like = Place.LIKE_TO_MASK.get(places[i].likeStr);

            places[i].setWeight(object.optInt("weight"));
            places[i].setDailyTimeHrs(object.optInt("dailyTime"));

            places[i].sessionId = sessionId;

            id = object.optInt("id");
            if (id > 0) {
                clustersLeft.add(cluster = clusters.clusters.get(id - 1));
                cluster.id = i;
                places[i].clusterId = i;
            } else {
                placesList.add(places[i]);
            }
//                places[i].timeParams = new RandomTimeParams[1];
//                places[i].timeParams[0] = Clustering.calcClusterOfClustersRndTimeParams(clusters.get(id - 1));
//            } else {

            places[i].timeStr = object.optString("usualTime").toLowerCase();

            if (!"".equals(places[i].timeStr)) {
                String[] times = places[i].timeStr.split(",");
                for (String time : times) {
                    places[i].usualTimeMask |= Place.TIME_TO_MASK.get(time);
                }

//                    RandomTimeParams params = places[i].timeParams = new RandomTimeParams();
            }
//            }
        }

        if (clusters != null) {
            clusters.clusters = clustersLeft;
        }

////        StringBuilder builder = new StringBuilder();
//        try {
////            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
//            FileOutputStream out = new FileOutputStream("/media/Data/Documents/tmp/clusters.bin");
////            ObjectOutputStream objectOutputStream = new ObjectOutputStream();
//            ObjectOutputStream objectOutputStream = new ObjectOutputStream(out);
//            objectOutputStream.writeObject(clusters);
////            byte[] bytes = byteArrayOutputStream.toByteArray();
////            for (byte b : bytes) {
////                builder.append(b).append(", ");
////            }
//            out.close();
//        } catch (IOException e) {
//            e.printStackTrace();
//        }


        routes = Clustering.detectRoutes2(clusters, placesList);

        try {
            DataBase db = DataBase.getInstance();
            db.insertPlaces(places);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    public List<Route> getRoutes() {
        return routes;
    }

    public void setRoutes(List<Route> routes) {
        this.routes = routes;
    }

    public void setTestClusters() {
    }
}

src/ru/samis/questionnaire/VkBean.java
package ru.samis.questionnaire;

import com.vk.api.sdk.client.TransportClient;
import com.vk.api.sdk.client.VkApiClient;
import com.vk.api.sdk.client.actors.UserActor;
import com.vk.api.sdk.exceptions.ApiException;
import com.vk.api.sdk.exceptions.ClientException;
import com.vk.api.sdk.exceptions.OAuthException;
import com.vk.api.sdk.httpclient.HttpTransportClient;
import com.vk.api.sdk.objects.UserAuthResponse;
import com.vk.api.sdk.objects.users.Occupation;
import com.vk.api.sdk.objects.users.UserXtrCounters;
import com.vk.api.sdk.queries.users.UserField;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

import ru.samis.questionnaire.db.DataBase;

//@Stateful(name = "ejb")
@ManagedBean(name = "vk")
@SessionScoped
public class VkBean {
    private static final int APP_ID = 6217258;
    private static final String REDIRECT_URI = "http://ssp.geosamara.ru/q/geodata.xhtml",
    //    private static final String REDIRECT_URI = "https://oauth.vk.com/blank.html",
    CLIENT_SECRET = "bkIhgETUU0ejVZ0AS0c8";

    private VkApiClient vk;
    private UserActor actor;

    private String person = "";

    private boolean authorized = false;


    private PersonalData personalData = new PersonalData();

    public PersonalData getPersonalData() {
        return personalData;
    }

    public void setPersonalData(PersonalData personalData) {
        this.personalData = personalData;
    }

    public void setPerson(String json) {
        person = json;
    }

    public String getPerson() {
        return person;
    }


    public boolean isAuthorized() {
        return authorized;
    }

    public int getAppId() {
        return APP_ID;
    }

    public String getRedirectUri() {
        return REDIRECT_URI;
    }

    public VkBean() {

    }


    public boolean authorizeInVK(String code) {

        if (!authorized) {
            if (vk == null) {
                TransportClient transportClient = HttpTransportClient.getInstance();

                vk = new VkApiClient(transportClient);
            }

            UserAuthResponse authResponse = null;
            try {
                authResponse = vk.oauth()
                                 .userAuthorizationCodeFlow(APP_ID, CLIENT_SECRET,
                                                            REDIRECT_URI, code
                                 ).execute();
                actor = new UserActor(authResponse.getUserId(), authResponse.getAccessToken());

                initFromVK();

                return authorized = true;
            } catch (OAuthException e) {
                e.getRedirectUri();
            } catch (ApiException e) {
                e.printStackTrace();
            } catch (ClientException e) {
                e.printStackTrace();
            }
            return authorized = false;
        }
        return authorized;
    }

    private void initFromVK() throws ClientException, ApiException {
        List<UserXtrCounters> counters = vk.users()
                                           .get(actor)
                                           .fields(
                                                   UserField.BDATE,
                                                   UserField.CITY,
                                                   UserField.EDUCATION,
                                                   UserField.SEX,
                                                   UserField.RELATIVES,
                                                   UserField.RELATION,
                                                   UserField.PERSONAL,
                                                   UserField.OCCUPATION,
                                                   UserField.SCHOOLS
                                           )
                                           .execute();
        UserXtrCounters user = counters.get(0);

        personalData.setSex(user.getSex().getValue());
        personalData.setSexFromVK(true);
        personalData.setCity(user.getCity().getTitle());
        personalData.setCityFromVK(true);

        String[] bdateComponents = user.getBdate().split("\\.");
        if (bdateComponents.length == 3) {
            int age;
            Calendar birth = Calendar.getInstance();
            Calendar calendar = Calendar.getInstance();
            birth.set(Integer.parseInt(bdateComponents[2]),
                      Integer.parseInt(bdateComponents[1]) - 1,
                      Integer.parseInt(bdateComponents[0]),
                      0, 0, 0);
            age = calendar.get(Calendar.YEAR) - birth.get(Calendar.YEAR);
            if (calendar.get(Calendar.MONTH) < birth.get(Calendar.MONTH)) {
                age--;
            } else if (calendar.get(Calendar.MONTH) == birth.get(Calendar.MONTH) &&
                       calendar.get(Calendar.DAY_OF_MONTH) < birth.get(Calendar.DAY_OF_MONTH)) {
                age--;
            }
            personalData.setAge(age);
            personalData.setAgeFromVK(true);
        }

        Occupation occupation = user.getOccupation();
        if (occupation != null && "university".equals(occupation.getType())) {
            String educationStatus = user.getEducationStatus();
            if (educationStatus != null && educationStatus.contains("Выпускник")) {
                personalData.setEdu(PersonalData.EDU_HIGH);
                personalData.setEduFromVK(true);
            } else {
                personalData.setEdu(PersonalData.EDU_HIGH_UNFINISHED);
                personalData.setEduFromVK(true);
            }
        }

        Integer relation = user.getRelation();
        if (PersonalData.ALLOWED_FAMILY_STATUSES.contains(relation)) {
            personalData.setFamilyStatus(relation);
            personalData.setFamilyFromVK(true);
        }
    }

    public String savePersonalDataToDb() throws ClassNotFoundException {
        FacesContext fCtx = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) fCtx.getExternalContext().getSession(false);
        if (session == null) {
            session = (HttpSession) fCtx.getExternalContext().getSession(true);
        }
        personalData.setSessionId(session.getId());
        try {
            DataBase db = DataBase.getInstance();
            db.insertPersonalData(personalData);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return "places";
    }
}

web/end.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
> <!--<![endif]-->
<h:head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Template</title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="Content/css/normalize.css"/>

    <!-- Styles section -->
    <link rel="stylesheet" href="Content/css/reset.css"/>
    <link rel="stylesheet" href="Content/css/global.css"/>
    <link rel="stylesheet" href="Content/css/common.css"/>
    <link rel="stylesheet" href="Content/css/colors.css"/>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"/>
    <script>window.jQuery || document.write('&lt;script src="js/vendor/jquery-1.10.2.min.js">&lt;\/script>')</script>
    <script src="Content/js/vendor/jcarousel.min.js"/>
    <script src="Content/js/plugins.js"/>
    <script src="Content/js/main.js"/>
    <script src="Content/js/vendor/modernizr-2.6.2.min.js"/>


</h:head>
<h:body class="i-default">

    <div class="l-page-wrapper">
        <div class="l-page">

            <!-- Header -->
            <div class="b-header">

                <!-- Header logo -->
                <div class="b-logo b-logo_header">
                    <a href="/">
                        <img src="Content/img/elements/logo-big.png" alt=""/>
                    </a>
                </div>
                <!-- / Header logo -->


            </div>
            <!-- / Header -->

            <!-- Main navigation -->
            <div class="b-navigation">

                <!-- Main menu -->
                <ul class="b-menu b-menu_main">
                    <li class="b-menu__item">
                        <p class="b-menu__link">1. геоданные</p>
                    </li>
                    <li class="b-menu__item">
                        <p class="b-menu__link">2. социальный статус</p>
                    </li>
                    <li class="b-menu__item state-active">
                        <p class="b-menu__link">3. места</p>
                    </li>
                    <li class="b-menu__item">
                        <p class="b-menu__link">4. маршруты</p>
                    </li>
                    <li class="b-menu__item">
                        <p class="b-menu__link">5. анкета</p>
                    </li>
                    <li class="b-menu__item i-last">
                        <p class="b-menu__link">выводы и советы</p>
                    </li>
                </ul>
                <!-- / Main menu -->

            </div>
            <!-- / Main navigation -->


            <!-- Page heading -->
            <div class="b-page-heading">
                <h1>Спасибо, тест закончен</h1>
            </div>
            <!-- / Page heading -->


            <!-- Content -->
            <div class="b-content">

                <div class="l-cols">
                    <div class="l-col-content">

                    </div>

                </div>

            </div>
            <!-- / Content -->

            <h:outputScript>
                <c:if test="#{geo.places == null and geo.clusters!=null}">
                    <c:forEach items="#{geo.clusters}" var="place" varStatus="i">
                        points.push({
                        "id": #{i.index+1},
                        "name": "Непонятное место #{i.index+1}",
                        "x1": #{place.lat},
                        "y1": #{place.lng},
                        "x2": #{place.lat+0.001},
                        "y2": #{place.lng+0.001},
                        "weight": #{place.weight}
                        });

                    </c:forEach>
                </c:if>
                <c:if test="#{geo.places != null}">
                    <c:forEach items="#{geo.places}" var="place">
                        points.push({
                        "name": "#{place.name}",
                        "x1": #{place.lat},
                        "y1": #{place.lng},
                        "x2": #{place.lat2},
                        "y2": #{place.lng2},
                        "weight": #{place.weight},
                        "type": "#{place.typeStr}"
                        <c:if test="#{!''.equals(place.likeStr)}">,
                            "likeThisPlace": "#{place.likeStr}"
                        </c:if>
                        <c:if test="#{!''.equals(place.timeStr)}">,
                            "usualTime": "#{place.timeStr}"
                        </c:if>
                        });

                    </c:forEach>
                </c:if>
            </h:outputScript>

            <script>
                updatePointsList();
            </script>


        </div>
    </div>

    <!-- Footer -->
    <div class="b-footer-wrapper">
        <div class="b-footer">
            <div class="b-footer__content">
                <div class="b-footer__copy">
                    &#169; Разработчики, 2016
                </div>
                <div class="b-footer__social">
                    Проект в сетях
                    <a href="#"><img src="Content/img/icons/icon-social-twitter.png" alt=""/></a>
                    <a href="#"><img src="Content/img/icons/icon-social-facebook.png" alt=""/></a>
                </div>
                <div class="b-footer__links">
                    <a href="#">О проекте</a>
                    <a href="#">Справка</a>
                    <a href="#">Обратная связь</a>
                </div>
            </div>
        </div>
    </div>
    <!-- / Footer -->


</h:body>
</html>

web/places.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html >
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
> <!--<![endif]-->
<h:head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>Template</title>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="Content/css/normalize.css"/>

    <!-- Styles section -->
    <link rel="stylesheet" href="Content/css/reset.css"/>
    <link rel="stylesheet" href="Content/css/global.css"/>
    <link rel="stylesheet" href="Content/css/common.css"/>
    <link rel="stylesheet" href="Content/css/colors.css"/>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"/>
    <script>window.jQuery || document.write('&lt;script src="js/vendor/jquery-1.10.2.min.js">&lt;\/script>')</script>
    <script src="Content/js/vendor/jcarousel.min.js"/>
    <script src="Content/js/plugins.js"/>
    <script src="Content/js/main.js"/>
    <script src="Content/js/vendor/modernizr-2.6.2.min.js"/>


</h:head>
<h:body class="i-default">


    <div class="l-page-wrapper">
        <div class="l-page">

            <!-- Header -->
            <div class="b-header">

                <!-- Header logo -->
                <div class="b-logo b-logo_header">
                    <a href="/">
                        <img src="Content/img/elements/logo-big.png" alt=""/>
                    </a>
                </div>
                <!-- / Header logo -->


            </div>
            <!-- / Header -->

            <!-- Main navigation -->
            <div class="b-navigation">

                <!-- Main menu -->
                <ul class="b-menu b-menu_main">
                    <li class="b-menu__item">
                        <p class="b-menu__link">1. геоданные</p>
                    </li>
                    <li class="b-menu__item">
                        <p class="b-menu__link">2. социальный статус</p>
                    </li>
                    <li class="b-menu__item state-active">
                        <p class="b-menu__link">3. места</p>
                    </li>
                    <li class="b-menu__item">
                        <p class="b-menu__link">4. маршруты</p>
                    </li>
                    <li class="b-menu__item">
                        <p class="b-menu__link">5. анкета</p>
                    </li>
                    <li class="b-menu__item i-last">
                        <p class="b-menu__link">выводы и советы</p>
                    </li>
                </ul>
                <!-- / Main menu -->

            </div>
            <!-- / Main navigation -->


            <!-- Page heading -->
            <div class="b-page-heading">
                <h1>3 шаг - Уточнение мест</h1>
            </div>
            <!-- / Page heading -->


            <!-- Content -->
            <div class="b-content">

                <div class="l-cols">
                    <div class="l-col-content">

                        <div class="b-text-page">
                            <p/>
                            <p>Мы распознали несколько мест, в которых вы часто бываете.</p>
                            <p>Помогите уточнить значение этих мест в вашей жизни.</p>
                            <p>И добавьте вручную часто посещаемые места, которые мы не смогли распознать.</p>
                            <p/>
                        </div>


                        <div>


                        </div>

                        <div class="b-text-page">


                            <div style="width: 500px; height: 400px; float:left;" id="mapContainer">

                                <script src="http://map.samadm.ru/js/geoMap.js"/>
                                <script src="Content/js/places.js"/>

                            </div>

                            <div style="width: 200px; height: 400px; float:left;" id="pointsListContainer">
                                <div style="height: 350px; margin: 0px 10px 10px 10px; overflow: scroll;"
                                     id="pointsList">

                                </div>
                                <input type="button" class="f-button"
                                       style="width: 180px; height: 30px; margin: 0px 10px 10px 10px;"
                                       value="добавить место" onclick="addPointHandler();" id="addPointButton"
                                       name="addPointButton"/>

                            </div>

                            <div style="width: 700px; float:left;" id="pointsTypeButtonsContainer">

                            </div>

                            <div style="width: 700px; float:left;" id="pointsOptionsContainer">

                            </div>


                        </div>

                        <div class="g-clear"/>

                        <div class="b-form b-properties_form">
                            <div class="b-form__row">
                                <div class="b-geo__begin">
                                    <h:form id="pointForm">
                                        <h:inputHidden id="points" value="#{geo.pointsJson}"/>

                                        <h:commandButton value="Следующий шаг" class="f-button"
                                                         onclick="return postPointsJson();"
                                                         action="routes"/>
                                    </h:form>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>

            </div>
            <!-- / Content -->

            <h:outputScript>
                <c:if test="#{geo.places == null and geo.clusters!=null}">
                    <c:forEach items="#{geo.clusters.clusters}" var="cluster" varStatus="i">
                        points.push({
                        "id": #{cluster.id+1},
                        "name": "Непонятное место #{i.index+1}",
                        "x1": #{cluster.lat},
                        "y1": #{cluster.lng},
                        "x2": #{cluster.lat+0.001},
                        "y2": #{cluster.lng+0.001},
                        "weight": #{cluster.weight}
                        });

                    </c:forEach>
                </c:if>
                <c:if test="#{geo.places != null}">
                    <c:forEach items="#{geo.places}" var="place">
                        points.push({
                        "id": #{place.clusterId+1},
                        "name": "#{place.name}",
                        "x1": #{place.lat},
                        "y1": #{place.lng},
                        "x2": #{place.lat2},
                        "y2": #{place.lng2},
                        "weight": #{place.weight},
                        "type": "#{place.typeStr}"
                        <c:if test="#{!''.equals(place.likeStr)}">,
                            "likeThisPlace": "#{place.likeStr}"
                        </c:if>
                        <c:if test="#{!''.equals(place.timeStr)}">,
                            "usualTime": "#{place.timeStr}"
                        </c:if>
                        <c:if test="#{place.dailyTimeHrs>0}">,
                            "dailyTime": "#{place.dailyTimeHrs}"
                        </c:if>
                        });

                    </c:forEach>
                </c:if>
                updatePointsList();
            </h:outputScript>

        </div>
    </div>

    <!-- Footer -->
    <div class="b-footer-wrapper">
        <div class="b-footer">
            <div class="b-footer__content">
                <div class="b-footer__copy">
                    &#169; Разработчики, 2016
                </div>
                <div class="b-footer__social">
                    Проект в сетях
                    <a href="#"><img src="Content/img/icons/icon-social-twitter.png" alt=""/></a>
                    <a href="#"><img src="Content/img/icons/icon-social-facebook.png" alt=""/></a>
                </div>
                <div class="b-footer__links">
                    <a href="#">О проекте</a>
                    <a href="#">Справка</a>
                    <a href="#">Обратная связь</a>
                </div>
            </div>
        </div>
    </div>
    <!-- / Footer -->


</h:body>
</html>